### ISSUE TITLE
Make relative context path configurable

### ISSUE THREAD

**Issue by tupadr3** [sonatype/docker-nexus3#1]
The nexus 2 image provides the possibility to define the relative context path. This would be a nice to have for this image as well.

**Comment by antoinebody** [comment]
+1 @tupadr3 : need it also to deploy nexus behind an nginx

**Comment by hakan42** [comment]
Any progress on this? I really would love to avoid patching the Dockerfile myself :smiling_imp:

**Comment by RobWin** [comment]
+1

**Comment by dbradicich** [comment]
A PR has been created adding such functionality https://github.com/sonatype/docker-nexus3/pull/19

**Comment by DarthHater** [comment]
Resolved in #40
