### ISSUE TITLE
Publish on docker hub

### ISSUE THREAD

**Issue by velo** [sonatype/docker-nexus3#10]
![image](https://cloud.githubusercontent.com/assets/136590/15639952/3ad56258-2686-11e6-9ff7-89f3cfdf318e.png)

Seems it's not there yet, would be nice to have it.

**Comment by joedragons** [comment]
@velo "docker search nexus3" returns the below, I believe it's there:
NAME                           DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
sonatype/nexus3                Sonatype Nexus Repository Manager 3             39
