### ISSUE TITLE
Update Readme.MD

### ISSUE THREAD

**Issue by wlumetsberger** [sonatype/docker-nexus3#11]
The part for Persistend Data is outdated. 
It is possible to use named volumes in docker which means there is no need for running the first container.
For Example:
to create the volume: `docker volume create --name nexusData`
to link the volume and start the container `docker run -d -p 8081:8081 --name nexus -v nexusData:/nexus-data sonatype/nexus3`

**Comment by DarthHater** [comment]
@wlumetsberger thanks for the info! Updated.
