### ISSUE TITLE
Permission denied for cfg files

### ISSUE THREAD

**Issue by jchannon** [sonatype/docker-nexus3#12]
I literally ran `docker run -d -p 8081:8081 --name nexus sonatype/nexus3` from README and it didn't start properly as CURL failed and below is what I got from looking at the logs.

I'm using docker v 1.11.1

Any ideas?

<img width="1490" alt="screen shot 2016-06-14 at 09 41 47" src="https://cloud.githubusercontent.com/assets/105126/16036594/8d5bc258-3214-11e6-97bb-27533a39d61c.png">

**Comment by joao-parana** [comment]
@jchannon , why you closed this issue ?  I received the same message today. How to resolve this ?
