### ISSUE TITLE
Bump docker hub push to 3.0.1

### ISSUE THREAD

**Issue by blue666man** [sonatype/docker-nexus3#15]
Last push was 3 months ago.  Would appreciate an updated version.

Thanks,
John

**Comment by frekele** [comment]
+1

**Comment by digitalLumberjack** [comment]
+1 please create an automated build based on the github releases :)

**Comment by joedragons** [comment]
Resolved by https://github.com/sonatype/docker-nexus3/pull/17.

**Comment by abcfy2** [comment]
But docker hub is still 3.0.0: https://hub.docker.com/r/sonatype/nexus3/tags/

**Comment by joedragons** [comment]
I apologize, I misread this one.

**Comment by nartamonov** [comment]
+1

**Comment by bobbyhubbard** [comment]
+1

**Comment by bsevero** [comment]
+1

**Comment by bdito** [comment]
+1

**Comment by ekho** [comment]
+1

**Comment by frekele** [comment]
The official repository Sonatype nexus, is not being updated.
It is ignoring the community's requests. :disappointed: 

Use this repository: 
https://github.com/frekele/docker-nexus
This image is using s6 as a process supervisor.
````
docker run --name nexus -p 8081:8081 frekele/nexus
```
 :smiley: :confetti_ball:

**Comment by frekele** [comment]
The official repository Sonatype nexus, is not being updated.
It is ignoring the community's requests. :disappointed: 

Use this repository: 
https://github.com/frekele/docker-nexus
This image is using s6 as a process supervisor.

Example:
````
docker run --name nexus -p 8081:8081 frekele/nexus
```
or by specifying the version:
````
docker run --name nexus -p 8081:8081 frekele/nexus:3.0.1-01
```

 :smiley: :confetti_ball:

**Comment by sdomula** [comment]
Still not updated on dockerhub. 😞  Is there a chance that it will be updated?

**Comment by tiagolo** [comment]
+1

**Comment by cgoeller** [comment]
+1

**Comment by digitalLumberjack** [comment]
https://docs.docker.com/docker-hub/builds/ seems to be a good solution :)

**Comment by tubbynl** [comment]
how about the other image? it seems to be automatically built https://hub.docker.com/r/sonatype/docker-nexus3/

**Comment by kellyrob99** [comment]
Sorry all, we've been working to get this part of our larger overall release process. 
New versions are available under the (absolutely right @tubbynl ) new auto-built image name: https://hub.docker.com/r/sonatype/docker-nexus3/tags/
