### ISSUE TITLE
Docker Nexus 3 as Docker Registry

### ISSUE THREAD

**Issue by fthamura** [sonatype/docker-nexus3#2]
Any idea to setup docker-nexus3 as docker-registry?

**Comment by jarosite** [comment]
I am faced with the same trouble. Docker repo is absent in list of available for creation repositories. Only maven2 and raw there.

**Comment by firehist** [comment]
Hey here, for me Docker repo is available.
![2016-05-12_09-59-29](https://cloud.githubusercontent.com/assets/449520/15266742/39db08e6-19af-11e6-878f-1b038843ae94.png)

I also have a question about Docker Registry. How set-up port 5000 & SSL certificates under this docker ?

**Comment by kellyrob99** [comment]
Instructions on how to configure Docker registries, including certificates, can be found here: https://books.sonatype.com/nexus-book/3.0/reference/docker.html

**Comment by MTon** [comment]
> I am faced with the same trouble. Docker repo is absent in list of available for creation repositories. Only maven2 and raw there.

Same for me here, but the bundle seems to be active

```
bundleId	212
name	com.sonatype.nexus.plugins:nexus-repository-docker
symbolicName	com.sonatype.nexus.plugins.nexus-repository-docker
location	mvn:com.sonatype.nexus.plugins/nexus-repository-docker/3.0.0-03
version	3.0.0.03
state	Installed
startLevel	200
fragment	false
````

The link to the documentation is quite useless in this case as described the option for docker repositories is missing!

Any help on this?

**Comment by jarosite** [comment]
@MTon,  are running official docker image? I resolved my issue by installing official distributive to fresh vm.

**Comment by mbacodes** [comment]
Yes I used `docker run -d -p 8081:8081 --name nexus sonatype/nexus3`.

**Comment by jagedn** [comment]
at least with Nexus OSS 3.0.2-02 you need to activate the docker bundle.

activate the karaf console (vi bin/nexus.vmoptions and set karaf.startLocalConsole=true)

bin/nexus run   (and press enter when log end)

karaf@root()> bundle:list  to find the id of docker bundle (in mi case 212)

karaf@root()> bundle:start 212

**Comment by kellyrob99** [comment]
@jagedn Not sure why you are seeing that behaviour, I just run the latest version available from Dockerhub and the Docker bundle is definitely loaded and available.

> docker run -d -p 8081:8081 --name nexus sonatype/docker-nexus3:3.0.2

Can you please provide some additional info as to how you're running the container and I can take a look?

**Comment by jagedn** [comment]
Sorry, my mistake. I didn't realize this project is about **dockerize** the nexus installation.
I installed the **zip version** into a fresh server and, as @MTon,  I couldn't find the docker repository. After searching a solution I found this issue that gave me the clue about how to activate it and I wanted to share it with you

**Comment by DarthHater** [comment]
@fthamura @jagedn I am unable to replicate this. If I run our docker image I see the ability to create the docker registry. Mind emailing me with more information if you are still experiencing this? jhesse at sonatype dot com
