### ISSUE TITLE
Add Upgrade Information to README.MD

### ISSUE THREAD

**Issue by tobiashochguertel** [sonatype/docker-nexus3#23]
I've upgrade my nexus3 to the latest version. I had trouble to start the new version 3.0.1.01 with my volume (nexus-data) from previos version 3.0.0... 

I found the solution in the release Notes/Upgrade notes: https://support.sonatype.com/hc/en-us/articles/217967608-How-to-Upgrade-to-Nexus-Repository-Manager-3

```
Make sure the old Nexus 3 installation is not running.

Manually backup the contents of the previous Data Directory to another location.

Inside your previous Data Directory, manually create an empty file named clean_cache
Example: /app/nexus3/data/clean_cache
```

**Comment by kellyrob99** [comment]
@tobiashochguertel This will no longer be an issue as of our 3.1 release, in which we instituted an automatic cleanup of the karaf cache on each start of the container.
