### ISSUE TITLE
EXTRA_JAVA_OPTS is ignored

### ISSUE THREAD

**Issue by jolangbein** [sonatype/docker-nexus3#24]
As far as I can see, the environment variable  `EXTRA_JAVA_OPTS` is not taken into account when Nexus is starting. 

This is due to the start script `/opt/sonatype/nexus/bin/nexus` of Nexus in Version 3.0.1-01 (due to `ENV NEXUS_VERSION 3.0.1-01`in `Dockerfile`) This script does not reference `EXTRA_JAVA_OPTS`

Nexus 3.1.0-SNAPSHOT however takes this into account in its start script (see https://github.com/sonatype/nexus-public/blob/814fdccf8fd20c7571381f7949eba49cf7edbb06/assemblies/nexus-base-template/src/main/resources/overlay/bin/nexus), so I think the `Dockerfile` is "ahead" of the latest published Nexus version.

**Comment by Rotwang** [comment]
I had the same issue, as a work around I've used `INSTALL4J_ADD_VM_PARAMS`

**Comment by GerritErpenstein** [comment]
The `NEXUS_CONTEXT` variable seems to be ignored too.

**Comment by DarthHater** [comment]
@Rotwang @jolangbein due to our internal use of Install4J, that is the correct way of going about this.
