### ISSUE TITLE
Migration from nexus2 docker image

### ISSUE THREAD

**Issue by ntdaley** [sonatype/docker-nexus3#26]
The blog at
   http://www.sonatype.org/nexus/2016/05/11/migrating-to-nexus-repository-3-easy-peasy/ 
recommends installing sonatype 2.14, and using its migration wizard as part of migrating to nexus 3.

But, there is no sonatype/nexus image tagged for v2.14.

To migrate from nexus 2, does a v2.14 image for sonatype/nexus need to be created?
If not, then perhaps some documentation on migrating from nexus 2 (within the context of docker) should be linked from the README.md

**Comment by joedragons** [comment]
@ntdaley 2.14 is not out yet, the article was written in advance.  You'll note it says "upcoming 2.14".  Stay tuned, we'll get this updated when it's out.  Thanks.
