### ISSUE TITLE
Updating Docker container from 3.0.0-03 to 3.0.2 breaks

### ISSUE THREAD

**Issue by InfoSec812** [sonatype/docker-nexus3#28]
I get a massive load of stack traces about being unable to load items from the OSGI bundle repository... Please help!!!

See attached output log
[nexus_errors.txt](https://github.com/sonatype/docker-nexus3/files/470754/nexus_errors.txt)

**Comment by InfoSec812** [comment]
Aha! I figured it out!! You have to delete the `cache` directory from `nexus_data` volume and it starts right up!

**Comment by ampedandwired** [comment]
Creating an empty file named `clean_cache` in the nexus data directory prior to the upgrade made everything work OK for me. As described here: https://support.sonatype.com/hc/en-us/articles/217967608-How-to-Upgrade-to-Nexus-Repository-Manager-3

**Comment by joedragons** [comment]
Thanks for the clarify @InfoSec812 and the document link @ampedandwired.
This is also addressed automatically in 3.1 so I'm closing this out.  If issues are seen with the 3.1 link or the documented solution please feel free to raise them here or in a new issue.

**Comment by InfoSec812** [comment]
Thanks Joe
