### ISSUE TITLE
Which version of Nexus3

### ISSUE THREAD

**Issue by fenchu** [sonatype/docker-nexus3#3]
Hi

Which version of nexus3 is this based on, the latest I have is milestone7:
https://support.sonatype.com/hc/en-us/articles/215781148-Nexus-Repository-Manager-3-0-Milestone-7-Release-

I'm unable to find anything newer.

Milestone7 is missing some features and I never got the docker behind sslproxy to work.
NPM package management was a big improvement though.

Really looking forward to a docker registry with proper management and caching.
Great work
--
MortenB, Oslo, Norway

**Comment by frekele** [comment]
Download Nexus Repository Manager 3 OSS

Consult our Nexus Repository Manager 3 guides for install and system requirements. This release does not require a license to be installed, however all existing licensed repository manager accounts are entitled to full technical support.

Unix archive: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-unix.tar.gz

Unix installer: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-unix.sh

Windows archive: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-win64.zip

Windows installer: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-win64.exe

OSX archive: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-mac.tgz

OSX installer: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-mac.dmg


REF:
https://support.sonatype.com/hc/en-us/articles/218637467-Download-Nexus-Repository-Manager-3

**Comment by frekele** [comment]
In Dockerfile is specified the 3.0.0-03 version Release, with Oracle JDK  8.77.03.
ENV NEXUS_VERSION 3.0.0-03
