### ISSUE TITLE
Align with rhel image

### ISSUE THREAD

**Issue by garethahealy** [sonatype/docker-nexus3#44]
Now theres a RHEL based image, would be nice if this and that, was aligned / same "code style"

i.e.: 
- multi line ENV vs single line
- yum install java vs curl / unzip

https://github.com/sonatype/docker-rhel-nexus/blob/master/Dockerfile

**Comment by DarthHater** [comment]
@garethahealy the single line ENV will be coming to the rhel Dockerfile, it's in testing. As for yum install java, feel free to hit me with a PR :)

**Comment by whyjustin** [comment]
@DarthHater @garethahealy styles update in #46 and https://github.com/sonatype/docker-rhel-nexus/commit/997bb8008bb4946231003495d1698af9c29e2d40. Some churn expected internally as we get on the same page for these Dockerfiles.
