### ISSUE TITLE
Issues upgrading with 3.0.1 => 3.0.2

### ISSUE THREAD

**Issue by cemo** [sonatype/docker-nexus3#47]
I need to update our docker nexus images with mounted volume but having some issues. Container does not start. 

When I add `clean_cache` file, it starts with some errors. The errors indicating a karaf errors like   `/opt/sonatype/nexus/etc/org.apache.karaf.command.acl.config.cfg (Permission denied)`

**Comment by DarthHater** [comment]
Hi there,

The issue you are encountering is known and is log spam. More here on that: https://issues.sonatype.org/browse/NEXUS-10049

As long as you can get Nexus running, you should be fine. Let me know!
