### ISSUE TITLE
[bug] /opt/sonatype/nexus/bin/nexus.vmoptions are not affected by memory environment variables provided to container

### ISSUE THREAD

**Issue by yilativs** [sonatype/docker-nexus3#5]
[bug] /opt/sonatype/nexus/bin/nexus.vmoptions is not affected by memory environment variables provided to container
java command line parameters 
-Xms256M
-Xmx768M
are hardcoded.

**Comment by agentgonzo** [comment]
I get the same thing. Setting JAVA_MAX_MEM and JAVA_MIN_MEM seems to get ignored:

Trying to set it to 512m, I get the following in the logs

2016-07-15 11:54:05,751+0000 WARN  [jetty-main-1] ```
*SYSTEM com.orientechnologies - Not enough physical memory available for DISKCACHE: 1,874MB (heap=1,150MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB
...
2016-07-15 11:54:35,659+0000 INFO  [FelixStartLevel]  org.elasticsearch.env - [D1B8CDDE-E9B40A5D-49440055-030137D8-D8FD6419] heap size [1.1gb], compressed ordinary object pointers [true]

```

**Comment by nartamonov** [comment]
Same trouble. Critical bug since april, it's a shame, Sonatype! :angry: 

As a workaround you can overwrite /opt/sonatype/nexus/bin/nexus.vmoptions inside container via volumes, see http://stackoverflow.com/questions/35705421/overwrite-files-with-docker-run.

**Comment by kaililleby** [comment]
another work around: use the INSTALL4J_ADD_VM_PARAMS env var, i.e. 
`docker ... -e INSTALL4J_ADD_VM_PARAMS="-Xms256M -Xmx768M"`

**Comment by mkristian** [comment]
@DarthHater any chance this can be fixed ? the bin/nexus launcher or any other code does not do anything with  this JAVA_MIN_MEM or JAVA_MAX_MEM environment variables ! all those workarounds are quite painful

**Comment by DarthHater** [comment]
This should be resolved by work that @bradbeck did in #72 , closing this and #66
