### ISSUE TITLE
Make a decision about the docker image

### ISSUE THREAD

**Issue by jeanblanchard** [sonatype/docker-nexus3#56]
PR #39 on October 12 changed the docker image references in the docs to "sonatype/docker-nexus3", to match the automated build on Docker Hub.
Then PR #54 on November 9 changed it back to "sonatype/nexus3".

On Docker Hub, "docker-nexus3" is the most up to date, but is marked as deprecated.

So what's the deal ? Which image is the right one ?

**Comment by DarthHater** [comment]
Hi there. We are in the middle of moving all the pieces around. In the near future we should have only one image, with multiple tags as you'd expect for what you want to run (IE 3.1. 3.0.0, etc..). I'll leave this open till we get it in place.

**Comment by kdekooter** [comment]
@DarthHater very well but which one is / will be deprecated?

A. sonatype/docker-nexus3
B. sonatype/nexus3

**Comment by paulvi** [comment]
👍 to @kdekooter Kees

README mentions `sonatype/nexus3`

**Comment by DarthHater** [comment]
This is done now. The images we will be using from this point forward are:

https://hub.docker.com/r/sonatype/nexus3/

You can pull it via `sonatype/nexus3`

The gh repo with the Dockerfile is this one, and you'll see that on the image in the hub, as well.
