### ISSUE TITLE
Fix Permissions For ${NEXUS_HOME}/etc

### ISSUE THREAD

**Issue by sherl0cks** [sonatype/docker-nexus3#57]
Currently ${NEXUS_HOME}/etc is owned by root and is not writable by the nexus user. This leads to various log statements like the below. I'm not sure if this creates functional issues, but it would be nice to have clean logs at a minimum.

- `[Timer-0] *SYSTEM java.util.prefs - Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock`
- `WARN  [pool-15-thread-1] *SYSTEM org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/karaf/org.apache.karaf.command.acl.system.cfg (Permission denied)`

**Comment by mcculls** [comment]
Those 'cfg' warnings don't cause any functional issues, they're informational messages from Karaf where it wants to touch certain files when deploying features and warns when it can't. But those files are optional because we ship a single ACL file, which is why it doesn't cause any functional issues.

Until this is fixed upstream you can use the following patch to remove those warnings:
```
diff --git a/Dockerfile b/Dockerfile
index c53c829..2f95a49 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -68,6 +68,15 @@ RUN sed \
     -i ${NEXUS_HOME}/etc/nexus-default.properties \
   && mkdir -p ${NEXUS_DATA}/etc ${NEXUS_DATA}/log ${NEXUS_DATA}/tmp
 
+# workaround NEXUS-10049 by touching the affected acl.cfg files
+RUN touch \
+    ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.feature.cfg \
+    ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.system.cfg \
+    ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.bundle.cfg \
+    ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.shell.cfg \
+    ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.config.cfg \
+    ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.jaas.cfg
+
 RUN useradd -r -u 200 -m -c "nexus role account" -d ${NEXUS_DATA} -s /bin/false nexus \
   && chown -R nexus:nexus ${NEXUS_DATA}
 ```

**Comment by sherl0cks** [comment]
Thanks @mcculls

**Comment by DarthHater** [comment]
Closing as this is a Karaf issue.
