### ISSUE TITLE
No support for Repository Connector port

### ISSUE THREAD

**Issue by laurent-opnworks** [sonatype/docker-nexus3#59]
To use Nexus 3 as a Private Registry for Docker and support "pushing" docker images to this private docker registry, the container must expose additional ports for Repository Connectors (see https://books.sonatype.com/nexus-book/3.1/reference/docker.html#docker-ssl-connector). The current image does not seem to support/expose more than one port so to use the docker image for this purpose it appears one must modify the docker image.

Would be nice to export additional ports such 8082, 8083, 8084 or whatever.

**Comment by DarthHater** [comment]
Unfortunately, not every user is going to need these ports exposed, and doing so would be bad practice. We try and expose the bare minimum that our users need to run Repository Manager itself.

If you are going to use https and Docker private registry, I suggest taking a look at this image that @bradbeck created: https://hub.docker.com/r/bradbeck/nexus-https/~/dockerfile/
