### ISSUE TITLE
[bug] nexus will not be stopped  gracefully during container stop because of incorrect CMD usage

### ISSUE THREAD

**Issue by yilativs** [sonatype/docker-nexus3#6]
Nexus will not be stopped  gracefully during container stop because of incorrect CMD usage

instead of 
CMD bin/nexus run
use
CMD ["/opt/sonatype/nexus/bin/nexus","run"]

see  https://docs.docker.com/engine/reference/builder/#cmd

**Comment by dbradicich** [comment]
Please open a pull request for your branch and we'll get it reviewed and merged

Thanks!

**Comment by DarthHater** [comment]
@yilativs @ryneo @jperville closing this as it should be fixed with the merge of #22
