### ISSUE TITLE
Hi, could you tell me  the password of the root user?

### ISSUE THREAD

**Issue by jeven2016** [sonatype/docker-nexus3#60]
Hi, could you tell me  the password of the root user?
Because my container failed to access the internet and I cannot trouble shoot with root privilege,  really appreciate for your reply , thanks.  : ）

**Comment by DarthHater** [comment]
Hi there,

You likely need to do something akin to this: http://stackoverflow.com/questions/28721699/root-password-inside-a-docker-container

Of note this is not an issue with this repo so I'm closing this issue.
