### ISSUE TITLE
Kubernetes deployment support

### ISSUE THREAD

**Issue by zlangbert** [sonatype/docker-nexus3#61]
I'd like to deploy nexus on kubernetes using persistent storage. The current container fails to start due to not having permissions to access the data volume. There is more detail in #13. The changes in that PR work nicely, but I thought I'd open an issue as well to see if we can get some movement on this. Thanks!

**Comment by paulvi** [comment]
Should there be a script to run on kubernetes?

Usually authers can't know themselves all possible ways how their software can be used. And if there is a bug with that, there should be a way to reproduce.

**Comment by zlangbert** [comment]
Generally you leave it up to the user to write the kubernetes deployment resources (though providing an example never hurts). The issue here is that when you provision a persistent volume in kubernetes it is owned by root. So the requirement in the readme `This directory needs to be writable by the Nexus process, which runs as UID 200`, makes things difficult. 

The strategy in #13 is a possible solution, i.e have the entrypoint make sure the permissions on the directory are correct.

There was also a comment posted a few days ago in a related kubeernetes [issue](https://github.com/kubernetes/kubernetes/issues/2630#issuecomment-275118375) with a way around this problem as well. Volume permissions seems to be an ongoing discussion in the kubernetes community.

The init container approach seems reasonable, so maybe just a note in the readme would suffice.

**Comment by donaldguy** [comment]
While example config-yamls for a Deployment or StatefulSet in this repo would be cool, even better would be an appropriately parameterized helm package, and ideally, one contributed upstream to https://github.com/kubernetes/charts

**Comment by donaldguy** [comment]
By way of encouragement, I will point out that https://github.com/kubernetes/charts/tree/master/incubator/artifactory already exists 😬

**Comment by DarthHater** [comment]
Moved to: https://issues.sonatype.org/browse/NEXUS-12860
