### ISSUE TITLE
Question: Will Nexus3 use docker images downloaded during installation of itself?

### ISSUE THREAD

**Issue by paulvi** [sonatype/docker-nexus3#63]
Will Nexus3 use docker images downloaded during installation of itself?

Or is it question: "can Nexus3 use docker repository on host system?" ?

Also asked on http://stackoverflow.com/questions/41808871/docker-images-proxy-server-private-docker-registry-using-nexus-oss-and-reusing

**Comment by DarthHater** [comment]
As a part of this base image, no. Not every user will need Docker repos exposed by default. As I replied in the SO question, you can likely use #48 as a good intro point to using the Provisioning API to do this.
