### ISSUE TITLE
What if I want nexus3 image to start from Ubuntu OS?

### ISSUE THREAD

**Issue by paulvi** [sonatype/docker-nexus3#64]
Currently it starts

     FROM       centos:centos7

What if I want nexus3 image to start from Ubuntu OS?

**Comment by joedragons** [comment]
@paulvi As far as I know changing to "FROM ubuntu:latest" (or whatever version) should work, though I've never tried it myself.  Centos7 is tested and supported thus it's the default in the dockerfile.

**Comment by DarthHater** [comment]
@paulvi I went ahead and created an example of this, you and others can check it out at the following link (DISCLAIMER: THIS IS NOT SUPPORTED BY SONATYPE :) ) 

https://github.com/DarthHater/docker-nexus3/blob/master/3.2/ubuntu/Dockerfile

I've not tested it extensively but in a quick dry run it worked. Bone apple teeth.
