### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by interone-ms** [sonatype/docker-nexus3#67]
Hi,

when uploading extremely huge (8+GB) docker image layers on a container with less RAM than the blob size, then the Java process appears to buffer all incoming data in RAM and subsequently break when the memory exhausts (only the upload fails, the container itself continues running as soon as the HTTP buffer is evicted from memory): 

2017-02-22 10:03:01,772+0000 WARN  [qtp1126292720-510] xxx org.sonatype.nexus.repository.docker.internal.V2Handlers - Error: PATCH /v2/xxxxxxxx/blobs/uploads/4ee41xxxxxxxxxc33ccd73
java.nio.channels.ClosedChannelException: null

Having to provision the equivalent amount of RAM that is expected for the maximum layer size is just horribly inefficient and expensive, please fix this.

**Comment by DarthHater** [comment]
Moved to: https://issues.sonatype.org/browse/NEXUS-12859

**Comment by rseddon** [comment]
This looks similar to an issue that another user reported. We were not able to reproduce this using the 3.3 release though.  Can you try using that version?  If you're still seeing a problem please file an issue at https://issues.sonatype.org in the "Dev - Nexus" project.
