### ISSUE TITLE
When container dies (not gracefully) cache.lock remains in nexus-data volume. Should not be persistent.

### ISSUE THREAD

**Issue by nieldw** [sonatype/docker-nexus3#69]
I use an NFS-backed (azure-file) data volume for /nexus-data. When the container dies non-gracefully, the cache lock file often [remains behind](http://stackoverflow.com/questions/41881273/kubernetes-cluster-has-oplock-samba-on-file-in-azure-storage-account) and has a NFS lock on it ("marked for deletion"), which prevents the container from restarting. As user tureba already pointed out in his comment on the [sonatype/nexus3](https://hub.docker.com/r/sonatype/nexus3/) repo on docker hub:

> Lock files, pid files, port files and (to some extent) temporary files are not supposed to be persisted! If the service dies suddenly and docker restarts it, we're in trouble if the pid files and lock files from the previous run are still in place because they will prevent the services from starting back up. **So they must not be in /nexus-data.**

_I'm pasting his comment here, since you can't link to it:_
![image](https://cloud.githubusercontent.com/assets/770125/24505218/646fa43a-1559-11e7-85d2-97594eeb1012.png)

**Comment by DarthHater** [comment]
Moved to: https://issues.sonatype.org/browse/NEXUS-12858
