### ISSUE TITLE
[bug] nexus.vmoptions is unmodifieable 

### ISSUE THREAD

**Issue by yilativs** [sonatype/docker-nexus3#7]
nexus.vmoptions is unmodifieable
there are various situations when a user might want to change parameters of nexus.vmoptions
such as changing memory consumption or
adding parameters that are not editable via UI for common maven repositories such as maven.oracle.com
-Dnexus.remoteStorage.enableCircularRedirectsForHosts=maven.oracle.com
-Dnexus.remoteStorage.useCookiesForHosts=maven.oracle.com

The solution for this problem would be either moving nexus.vmoptions to a volume with nexus_data 
or 
creating additional data volume
or
providing environment variables that are responsible for this parameters in a Dockerfile

**Comment by roman-vynar** [comment]
Place your custom nexus.properties into `<nexus-data-dir>/etc/nexus.properties` and it will work.
