### ISSUE TITLE
HTTP authentication fail with Docker private registry in Docker Hub

### ISSUE THREAD

**Issue by mmorejon** [sonatype/docker-nexus3#70]
Hi team,

I'm trying to pull a docker image from a private account. I'm using HTTP authentication option located at the end of docker proxy configuration but doesn't work. Where do I should setup username and password settings? 

![screen shot 2017-04-03 at 11 21 38 am](https://cloud.githubusercontent.com/assets/5578317/24616670/cd227210-185f-11e7-8c95-b5833ee9e12f.png)

**Comment by DarthHater** [comment]
Moved to: https://issues.sonatype.org/browse/NEXUS-12857
