### ISSUE TITLE
readme incorrectly describes how data volumes are used

### ISSUE THREAD

**Issue by peterlynch** [sonatype/docker-nexus3#71]
readme contains:

> "Since data volumes are persistent until no containers use them,"

This statement appears wrong.

Data volumes are not deleted when no container uses them. In fact data volumes are never removed by docker when containers are deleted. 

From https://docs.docker.com/engine/tutorials/dockervolumes/#data-volumes : 

> Data volumes persist even if the container itself is deleted.
> Data volumes are designed to persist data, independent of the container’s lifecycle. Docker therefore never automatically deletes volumes when you remove a container, nor will it “garbage collect” volumes that are no longer referenced by a container.

**Comment by DarthHater** [comment]
Moved to: https://issues.sonatype.org/browse/NEXUS-12856
