### ISSUE TITLE
Maven site repository no working

### ISSUE THREAD

**Issue by dkirrane** [sonatype/docker-nexus3#8]
When I run this container and create a hosted Maven site repository in 'raw' format it doesn't work.

I don't see any errors in Docker logs but I keep getting Error 404 Not Found for http://ip:8081/repository/site/

**Comment by joedragons** [comment]
@dkirrane I wonder if this is what you are seeing: https://issues.sonatype.org/browse/NEXUS-10113

**Comment by dkirrane** [comment]
Yip I raised that. I'll close this
